/*
=========================================================================

                        WinReceiverNDI.cpp

				Using ofxNDI (http://spout.zeal.co/)

   A Windows Desktop Application project generated by Visual Studio
   and adapted for NDI output (https://www.ndi.tv/)

   This is an example of using the ofxNDIreceive class independent of Openframeworks
   to receive to a pixel buffer and display the output using Windows bitmap functions.

   Functions used : 

	Receiver setup
		SetAudio
		SetFormat
	
	Receiver sender monitoring
		FindSenders
		GetSenderCount
		SenderSelected

	Receive sender pixels
		ReceiveImage

	Hold render frame rate
		HoldFps

	Select sender
		GetSenderList
		GetSenderIndex
   

   Compare with the Spout DirectX Windows example.

=========================================================================

                 Copyright(C) 2024-2026 Lynn Jarvis

   This program is free software : you can redistribute it and/or modify
   it under the terms of the GNU Lesser General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.See the
   GNU Lesser General Public License for more details.

   You should have received a copy of the GNU Lesser General Public License
   along with this program.If not, see < http://www.gnu.org/licenses/>.
========================================================================

15.05.24 - Example created - Version 1.000
19.05.26 - Revision
		   Initialize all variables
		   Replace resource dialogs with ofxNDIutils::MessageDialog
		   Simplify sender selection code
21.05.26   Rebuild with latest ofxNDI 2.003.000 - NDI 6.3.2.0 x64/MT
		   Version 2.000

*/
#include "framework.h"
#include "resource.h"
#include <vector>
#include "ofxNDIreceive.h"

#define MAX_LOADSTRING 100

// Global Variables:
HINSTANCE hInst = NULL;                // current instance
WCHAR szTitle[MAX_LOADSTRING]{};       // The title bar text
WCHAR szWindowClass[MAX_LOADSTRING]{}; // the main window class name

ofxNDIreceive receiver;                // Receiver object
HWND g_hWnd = NULL;                    // Window handle
unsigned char *pixelBuffer = nullptr;  // Receiving pixel buffer
unsigned int g_SenderWidth = 0;        // Received sender width
unsigned int g_SenderHeight = 0;       // Received sender height
double g_SenderFps = 0.0;              // For fps display averaging
bool bShowInfo = true;                 // Show on-screen info

// Forward declarations of functions included in this code module:
ATOM                MyRegisterClass(HINSTANCE hInstance);
BOOL                InitInstance(HINSTANCE, int);
LRESULT CALLBACK    WndProc(HWND, UINT, WPARAM, LPARAM);
INT_PTR CALLBACK    About(HWND, UINT, WPARAM, LPARAM);

void Render();
bool SelectSender();
void AboutBox();
void ShowSenderInfo(HDC hdc); // Show sender information on screen
void DrawString(std::string str, HDC hdc, COLORREF col, int xpos, int ypos); // Draw text


int APIENTRY wWinMain(_In_ HINSTANCE hInstance,
                     _In_opt_ HINSTANCE hPrevInstance,
                     _In_ LPWSTR    lpCmdLine,
                     _In_ int       nCmdShow)
{
    UNREFERENCED_PARAMETER(hPrevInstance);
    UNREFERENCED_PARAMETER(lpCmdLine);

 	
	// For debugging
	/*
	FILE* pCout; // should really be freed on exit
	AllocConsole();
	freopen_s(&pCout, "CONOUT$", "w", stdout);
	// Disable console close button to prevent accidental shutdown
	HMENU hmenu = GetSystemMenu(GetConsoleWindow(), FALSE);
	EnableMenuItem(hmenu, SC_CLOSE, MF_GRAYED);
	printf("WinReceiverNDI\n");
	*/

    // Initialize global strings
    LoadStringW(hInstance, IDS_APP_TITLE, szTitle, MAX_LOADSTRING);
    LoadStringW(hInstance, IDC_WIN_NDI, szWindowClass, MAX_LOADSTRING);
    MyRegisterClass(hInstance);

    // Perform application initialization:
    if (!InitInstance (hInstance, nCmdShow))
        return FALSE;

	// =======================================
	receiver.SetAudio(false); // Set to receive no audio

	// =======================================
	// Set to prefer BGRA to match with windows bitmpap format (see WM_PAINT)
	receiver.SetFormat(NDIlib_recv_color_format_BGRX_BGRA);

    // Main message loop:
	MSG msg = { 0 };
	while (WM_QUIT != msg.message)
	{
		if (PeekMessage(&msg, nullptr, 0, 0, PM_REMOVE))
		{
			TranslateMessage(&msg);
			DispatchMessage(&msg);
		}
		// Continue if a message is received
		// See HoldFps in Render for rate control
		{
			Render();
		}
	}

	// Free the pixel buffer
	if (pixelBuffer) delete[] pixelBuffer;

	// Release the receiver
	receiver.ReleaseReceiver();

    return (int) msg.wParam;
}


void Render()
{
	// Receive a pixel buffer from the NDI sender
	// Frame rate might be less than the draw cycle
	// ReceiveImage succeeds if it finds a sender
	// and creates a receiver if not initialized yet
	// or a new sender has been selected
	// Width and height can optionally be returned as unsigned int
	//     receiver.ReceiveImage(width, height)
	//
	if (receiver.ReceiveImage()) {

		// Have the sender dimensions changed ?
		if (g_SenderWidth  != receiver.GetSenderWidth()
		 || g_SenderHeight != receiver.GetSenderHeight()) {
			g_SenderWidth   = receiver.GetSenderWidth();
			g_SenderHeight  = receiver.GetSenderHeight();
			// Update the receiving pixel buffer
			if (pixelBuffer) free((void*)pixelBuffer);
			pixelBuffer = (unsigned char*)malloc(g_SenderWidth*g_SenderHeight*4*sizeof(unsigned char));
		}

		// In this example an independent pixel buffer is used
		// which is most likely adaptable for other applications

		// Copy received NDI video frame data to the local pixel buffer
		// CopyImage uses SSE2 functions if the width is 16bit aligned
		ofxNDIutils::CopyImage((const unsigned char*)receiver.GetVideoData(),
			pixelBuffer, g_SenderWidth, g_SenderHeight, receiver.GetVideoStride());

		// The NDI video frame data must be freed every frame
		// to prevent a memory leak. Alternatively, to avoid the
		// copy, the video data could be used directly in WM_PAINT
		// and the NDI data freed after that

		// Free NDI video frame data
		receiver.FreeVideoData();

		// Trigger a re-paint to draw the pixel buffer - see WM_PAINT
		InvalidateRect(g_hWnd, NULL, FALSE);

		// Update immediately
		UpdateWindow(g_hWnd);

	}
	else {
		// No senders or the sender closed
		// Take no action if the sender closed
		// Receiving will resume when it re-opens
	}


	// =======================================
	// Control the render cycle rate

	// Hold a target frame rate - e.g. 60 or 30fps.
	// This is not necessary if the application already has
	// fps control. But in this example, rendering is done
	// during idle time and render rate can be extremely high
	ofxNDIutils::HoldFps(30);

} // end Render


//
// Sender list selection dialog
//
bool SelectSender()
{
	// Refresh the NDI sources and get the sender count
	receiver.FindSenders();

	// Create a local sender list
	std::vector<std::string> senderlist = receiver.GetSenderList();
	if (!senderlist.empty()) {
		// MessageDialog with combobox returns the item index
		// No icon used to give a wider combo-box for long names
		int selected = receiver.GetSenderIndex();
		if (ofxNDIutils::MessageDialog(g_hWnd, NULL, "Select sender", MB_OKCANCEL, senderlist, selected) == IDOK) {
			//
			// Update the receiver with the returned index.
			// If the selected sender is different from the current one,
			// the receiver is released and the class sender name updated.
			// A new receiver is then created by ReceiveImage
			//
			if (receiver.SetSenderIndex(selected))
				std::cout << "Selected [" <<receiver.GetSenderName(selected) << "]" << std::endl;
			else
				std::cout << "Same sender" << std::endl;
		}
		return true;
	}
	else {
		// Add a caption 'X' for cancel like a conventional MessageBox
		ofxNDIutils::MessageDialogCancel(true);
		ofxNDIutils::MessageDialog(g_hWnd, "No senders found", "Warning", MB_OK | MB_ICONWARNING);
	}

	// No senders
	return false;

} // end SelectSender


// Resource dialog replaced by MessageDialog
void AboutBox() {
	std::string str;
	str =  "                      WinReceiverNDI\n\n";
	str += "             Windows NDI receiver example.\n";
	str += "              Receive to a pixel buffer using\n";
	str += "                 the ofxNDIreceive class.\n";
	str += "                     ofxNDI - " + ofxNDIutils::GetVersion() + "\n\n";
	str += "                    <a href=\"https://spout.zeal.co\">https://spout.zeal.co</a>\n";
	str += "                   <a href=\"https://www.ndi.video\">https://www.ndi.video</a>\n\n";
	ofxNDIutils::MessageDialogIcon(LoadIcon(hInst, MAKEINTRESOURCE(IDI_WIN_NDI)));
	ofxNDIutils::MessageDialog(g_hWnd, str.c_str(), "About", MB_OK);
}


void ShowSenderInfo(HDC hdc)
{
	std::string str = receiver.GetSenderName();
	str += "   : ";
	str += std::to_string(receiver.GetSenderWidth()); str += "x";
	str += std::to_string(receiver.GetSenderHeight());
	// Show sender fps    
	str += "   fps ";
	// Average to stabilise fps display
	g_SenderFps = g_SenderFps*.85 + 0.15*receiver.GetSenderFps();
	// Round first or integer cast will truncate to the whole part
	str += std::to_string((int)(round(g_SenderFps)));
	// Draw text
	DrawString(str, hdc, 0x00FFFFFF, 20, 20);
	str = "Right click - select sender   :   Space - hide info";
	DrawString(str, hdc, 0x00FFFFFF, 20, 42);

} // end ShowSenderInfo


void DrawString(std::string str, HDC hdc, COLORREF col, int xpos, int ypos)
{
	HFONT hFont = (HFONT)GetStockObject(SYSTEM_FONT);
	HFONT hOldFont = (HFONT)SelectObject(hdc, hFont);
	if (hOldFont)
	{
		// Text colour
		// Can be any colour (00 BB GG RR) hex
		// e.g. red = 0x000000FF
		COLORREF oldText = SetTextColor(hdc, col);
		// Transparent background
		SetBkMode(hdc, TRANSPARENT);
		// Display the text string
		TextOutA(hdc, xpos, ypos, str.c_str(), (int)str.length());
		SetTextColor(hdc, oldText);
		SelectObject(hdc, hOldFont);
	}
} // end DrawString


//
//  FUNCTION: MyRegisterClass()
//
//  PURPOSE: Registers the window class.
//
ATOM MyRegisterClass(HINSTANCE hInstance)
{
	WNDCLASSEXW wcex{};
    wcex.cbSize         = sizeof(WNDCLASSEX);
    wcex.style          = CS_HREDRAW | CS_VREDRAW;
    wcex.lpfnWndProc    = WndProc;
    wcex.cbClsExtra     = 0;
    wcex.cbWndExtra     = 0;
    wcex.hInstance      = hInstance;
    wcex.hIcon          = LoadIcon(hInstance, MAKEINTRESOURCE(IDI_WIN_NDI));
    wcex.hCursor        = LoadCursor(nullptr, IDC_ARROW);
	wcex.hbrBackground  = CreateHatchBrush(HS_DIAGCROSS, RGB(192, 192, 192));
    wcex.lpszMenuName   = MAKEINTRESOURCEW(IDC_WIN_NDI);
    wcex.lpszClassName  = szWindowClass;
	wcex.hIconSm = LoadIcon(wcex.hInstance, MAKEINTRESOURCE(IDI_WIN_NDI));

    return RegisterClassExW(&wcex);
}

//
//   FUNCTION: InitInstance(HINSTANCE, int)
//
//   PURPOSE: Saves instance handle and creates main window
//
//   COMMENTS:
//
//        In this function, we save the instance handle in a global variable and
//        create and display the main program window.
//
BOOL InitInstance(HINSTANCE hInstance, int nCmdShow)
{
   hInst = hInstance; // Store instance handle in our global variable

   // Create window
   RECT rc = { 0, 0, 640, 360 }; // Desired client size
   AdjustWindowRect(&rc, WS_OVERLAPPEDWINDOW, TRUE); // Allow for menu
   HWND hWnd = CreateWindowW(szWindowClass,
	   szTitle,
	   WS_OVERLAPPED | WS_CAPTION | WS_SYSMENU | WS_MINIMIZEBOX | WS_MAXIMIZEBOX | WS_THICKFRAME,
	   CW_USEDEFAULT, CW_USEDEFAULT, rc.right - rc.left, rc.bottom - rc.top, nullptr, nullptr, hInstance,
	   nullptr);

   if (!hWnd)
      return FALSE;

   // Centre the window on the desktop work area
   GetWindowRect(hWnd, &rc);
   RECT WorkArea{};
   int WindowPosLeft = 0;
   int WindowPosTop = 0;
   SystemParametersInfo(SPI_GETWORKAREA, 0, (LPVOID)&WorkArea, 0);
   WindowPosLeft += ((WorkArea.right  - WorkArea.left) - (rc.right - rc.left)) / 2;
   WindowPosTop  += ((WorkArea.bottom - WorkArea.top)  - (rc.bottom - rc.top)) / 2;
   MoveWindow(hWnd, WindowPosLeft, WindowPosTop, (rc.right - rc.left), (rc.bottom - rc.top), false);

   ShowWindow(hWnd, nCmdShow);
   UpdateWindow(hWnd);

   g_hWnd = hWnd;
   
   return TRUE;
}


//
//  FUNCTION: WndProc(HWND, UINT, WPARAM, LPARAM)
//
//  PURPOSE: Processes messages for the main window.
//
//  WM_COMMAND  - process the application menu
//  WM_PAINT    - Paint the main window
//  WM_DESTROY  - post a quit message and return
//
LRESULT CALLBACK WndProc(HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
{
    switch (message)
    {
		case WM_RBUTTONDOWN:
			// Right click to select a sender
			SelectSender();
			break;

		case WM_KEYUP:
		{
			// Space bar to show/hide on-screen text
			if (wParam == 0x20) {
				bShowInfo = !bShowInfo;
			}
			else {
				// Sender index selection by key press 0-9
				// For compatibility with the openframeworks example
				// (ofxNDI-example-receiver)
				int index = (int)wParam - 48; // The key pressed
				int nsenders = receiver.GetSenderCount();
				if (nsenders > 0 && index >= 0 && index < nsenders) {
					// Update the receiver with the key index
					if (receiver.SetSenderIndex(index))
						printf("[%s]\n", receiver.GetSenderName(index).c_str());
					else
						printf("Same sender\n");
				}
			}
		}
		break;

		case WM_COMMAND:
		{
			int wmId = LOWORD(wParam);
			// Parse the menu selections:
			switch (wmId)
			{
				case IDM_ABOUT:
					// About messagebox
					AboutBox();
					break;
				case IDM_OPEN:
					// Sender selection messagebox
					SelectSender();
					break;
				case IDM_EXIT:
					DestroyWindow(hWnd);
					break;
				default:
					return DefWindowProc(hWnd, message, wParam, lParam);
			}
		}
		break;

    case WM_PAINT:
        {
			// Draw the received image
			PAINTSTRUCT ps{};
			HDC hdc = BeginPaint(hWnd, &ps);
			RECT dr = { 0 };
			GetClientRect(hWnd, &dr);

			// Create a double buffer so that both image and text
			// can be drawn to a memory DC to avoid flicker.
			HDC hdcMem = CreateCompatibleDC(hdc);
			int ndcmem = SaveDC(hdcMem);
			HBITMAP hbmMem = CreateCompatibleBitmap(hdc, (dr.right-dr.left), (dr.bottom-dr.top));
			SelectObject(hdcMem, hbmMem);

			// No sender - draw default background
			if (!receiver.ReceiverConnected()) {
				HBRUSH backbrush = CreateHatchBrush(HS_DIAGCROSS, RGB(192, 192, 192));
				FillRect(hdc, &dr, backbrush);
				DeleteObject(backbrush);
			}
			else if (pixelBuffer) {

				// The received sender format is set to BGRA
				// with SetFormat(NDIlib_recv_color_format_BGRX_BGRA)
				// and matches the Windows bitmap
				BITMAPINFO bmi;
				ZeroMemory(&bmi, sizeof(BITMAPINFO));
				bmi.bmiHeader.biSize = sizeof(BITMAPINFOHEADER);
				bmi.bmiHeader.biSizeImage = (LONG)(g_SenderWidth * g_SenderHeight * 4); // Pixel buffer size
				bmi.bmiHeader.biWidth = (LONG)g_SenderWidth; // Width of buffer
				bmi.bmiHeader.biHeight = -(LONG)g_SenderHeight; // Height of buffer (negative for upside-down bitmap)
				bmi.bmiHeader.biPlanes = 1;
				bmi.bmiHeader.biBitCount = 32;
				bmi.bmiHeader.biCompression = BI_RGB;

				// Draw into the memory DC
				// For double buffer, setting the blit mode is necessary here
				SetStretchBltMode(hdcMem, STRETCH_DELETESCANS);

				// StretchDIBits adapts the pixel buffer received from the sender
				// to the window size. The sender can be resized or changed.
				StretchDIBits(hdcMem,
					0, 0, (dr.right - dr.left), (dr.bottom - dr.top), // destination rectangle 
					0, 0, g_SenderWidth, g_SenderHeight, // source rectangle 
					pixelBuffer,
					&bmi, DIB_RGB_COLORS, SRCCOPY);

				// Draw the sender information text unless no show by space bar
				if (bShowInfo)
					ShowSenderInfo(hdcMem);

				// Copy the double buffer to screen
				BitBlt(hdc, 0, 0, (dr.right-dr.left), (dr.bottom-dr.top), hdcMem, 0, 0, SRCCOPY);

				// Clean up
				RestoreDC(hdcMem, ndcmem);
				DeleteObject(hbmMem);
				DeleteDC(hdcMem);

			} // endif pixelBuffer
			EndPaint(hWnd, &ps);
        }
        break;

	case WM_DESTROY:
        PostQuitMessage(0);
        break;

    default:
        return DefWindowProc(hWnd, message, wParam, lParam);

    }
    return 0;
}

// That's all..
